name: uno
description: Uno is a multiplatform HTTP client, based on Axios and built following the Clean Dart approach by the Flutterando Community.
version: 1.1.9
homepage: https://github.com/Flutterando/uno.git

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies: 
  universal_io: '>=2.2.0 <3.0.0'
  characters: '>=1.2.1 <2.0.0'
  meta: '>=1.8.0 <2.0.0'
  mime_type: ^1.0.0
  path: '>=1.8.2 <2.0.0'
  file: '>=6.1.4 <7.0.0'

dev_dependencies:
  mocktail: ^0.3.0
  flutterando_analysis: ^0.0.2
  test: '>=1.10.0 <2.0.0'
