name: uno
description: Uno is a multiplatform HTTP client, based on Axios and built following the Clean Dart approach by the Flutterando Community.
version: 1.0.1+5
homepage: https://github.com/Flutterando/uno.git

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  universal_io: '>=2.0.4 <3.0.0'
  characters: '>=1.0.0 <2.0.0'
  meta: '>=1.3.0 <2.0.0'
  mime_type: ^1.0.0
  path: '>=1.4.0 <2.0.0'

dev_dependencies:
  mocktail: ^0.2.0
  flutterando_analysis: ^0.0.1
  test: '>=1.10.0 <2.0.0'
