name: uno
description: Future based HTTP client for the Dart and Flutter
version: 1.0.1+2
homepage: https://github.com/Flutterando/uno.git

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  universal_io: '>=2.0.4 <3.0.0'
  characters: '>=1.0.0 <2.0.0'
  meta: '>=1.3.0 <2.0.0'
  mime_type: ^1.0.0
  path: '>=1.4.0 <2.0.0'

dev_dependencies:
  mocktail: ^0.2.0
  pedantic: ^1.10.0
  test: '>=1.10.0 <2.0.0'